service: appnamecore

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1

custom:
  PathToSystemCore: ""
  system: ${file(custom.yml)}

# functions:
#   - ${file(functions.yml)}

resources:
  # - ${file(conditions.yml)} 
  - ${file(cognito.yml)}
  - ${file(api.yml)} 
  #- ${file(authoriser.yml)}
  - ${file(website.yml)} 
  - ${file(aurora.yml)}